# Generated by Django 4.2.2 on 2023-07-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]
    
    operations = [
    ]
