# Generated by Django 4.2.2 on 2023-07-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_category_donation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('password', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('repeat_password', models.CharField(max_length=255)),
            ],
        ),
    ]
