# Generated by Django 4.2.2 on 2023-07-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_login_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donor_name',
            new_name='Your_name',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donor_email',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donor_mobile',
            new_name='mobile_No',
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
