# Generated by Django 4.2.2 on 2023-07-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_rename_donor_name_donation_your_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='mobile_No',
            new_name='Mobile',
        ),
    ]
