# Generated by Django 4.2.2 on 2023-07-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0010_rename_address_donation_donor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password1', models.CharField(max_length=255)),
                ('password2', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
