# Generated by Django 4.2.2 on 2023-07-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0011_user_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField()),
                ('donor_email', models.EmailField(max_length=254)),
                ('Donation_type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
