# Generated by Django 4.2.2 on 2023-07-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0012_donors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
