# Generated by Django 4.2.2 on 2023-07-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0013_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='message',
            field=models.TextField(default='DEFAULT VALUE', max_length=1000),
        ),
    ]
