# Generated by Django 4.2.2 on 2023-07-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0014_donors_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='category',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
